### ISSUE TITLE
video does not show , just sound

### ISSUE THREAD

**Issue by mohammad-aqajani** [adnaniazi/pyplayer#1]
it does not show the video just the sound,

and also this : 
Traceback (most recent call last):
  File "main.py", line 178, in tick
    self.current_tick_time_str = self.convert_time_to_human_readable_format(tick_time)
  File "main.py", line 195, in convert_time_to_human_readable_format
    if (self.total_video_time_ms/1000) > 3600:
AttributeError: 'MyMainGui' object has no attribute 'total_video_time_ms'

**Comment by adnaniazi** [comment]
Does it happen for every video, or just one particular video file.

**Comment by mohammad-aqajani** [comment]
I have tested it with couple video formats, but still the same problem

**Comment by adnaniazi** [comment]
I am unable to recreate the issue at my end. Perhaps installing a media codec will help. Try installing this one:
https://www.microsoft.com/en-pk/download/details.aspx?id=6220

**Comment by mohammad-aqajani** [comment]
using ubuntu
phonon works properly with python in aother projects
